# \uC8FC\uC758! \uB4E4\uC5EC\uC4F0\uAE30 \uBBFC\uAC10!
spring:
  # DB \uC124\uC815
  h2:
    console:
      enabled: true
  # JPA \uC124\uC815
  jpa:
    show-sql: true # JPA \uB3D9\uC791 \uC2DC, \uB0B4\uBD80 SQL \uCD9C\uB825!
    properties:
      hibernate.format_sql: true # \uBCF4\uAE30 \uC88B\uAC8C \uCD9C\uB825!